export const baselineArtists = [
  { id: "artist-kaia-rivers", slug: "kaia-rivers", stageName: "Kaia Rivers", countryRegion: "Antigua & Barbuda", primaryGenre: "Soca", biography: "A bright new Wadadli voice blending modern soca energy with warm island storytelling.", verificationStatus: "verified", foundingArtist: true },
  { id: "artist-marlon-tide", slug: "marlon-tide", stageName: "Marlon Tide", countryRegion: "Antigua & Barbuda", primaryGenre: "Reggae", biography: "Roots-focused reggae shaped by harbour life, live musicianship, and Antiguan perspective.", verificationStatus: "verified", foundingArtist: true },
  { id: "artist-nia-vale", slug: "nia-vale", stageName: "Nia Vale", countryRegion: "Antigua & Barbuda", primaryGenre: "R&B", biography: "Late-night soul, island cadence, and fearless independent songwriting from St. John's.", verificationStatus: "verified", foundingArtist: true },
  { id: "artist-kruz-the-bay", slug: "kruz-and-the-bay", stageName: "Kruz & The Bay", countryRegion: "Antigua & Barbuda", primaryGenre: "Dancehall", biography: "A bass-forward Wadadli collective connecting live-band instinct with dancehall momentum.", verificationStatus: "unverified", foundingArtist: false },
  { id: "artist-elijah-stone", slug: "elijah-stone", stageName: "Elijah Stone", countryRegion: "Barbados", primaryGenre: "Afrobeat", biography: "Caribbean rhythm and melodic Afrobeat from an independent Barbadian songwriter.", verificationStatus: "unverified", foundingArtist: false },
  { id: "artist-lani-june", slug: "lani-june", stageName: "Lani June", countryRegion: "Dominica", primaryGenre: "Alternative", biography: "Soft coastal textures and alternative songwriting rooted in Dominica.", verificationStatus: "unverified", foundingArtist: false },
  { id: "artist-mika-machine", slug: "mika-and-machine", stageName: "Mika + Machine", countryRegion: "Antigua & Barbuda", primaryGenre: "Electronic", biography: "A disclosed AI-assisted experiment pairing human direction with future-island electronic production.", verificationStatus: "unverified", foundingArtist: false },
  { id: "artist-nova-palm", slug: "nova-palm", stageName: "Nova Palm", countryRegion: "Guest Frequency", primaryGenre: "Fusion", biography: "An independent global-bass project selected for ChuneSide's Guest Frequency lane.", verificationStatus: "unverified", foundingArtist: false },
] as const;

export const baselineReleases = [
  { id: "release-golden-hour", artistProfileId: "artist-kaia-rivers", legacyTrackId: 1, slug: "golden-hour", title: "Golden Hour", genre: "Soca", region: "Antigua & Barbuda", discoveryLane: "wadadli", creationType: "artist_made", mood: "Carnival glow", durationSeconds: 198, accentGradient: "from-[#ff4d00] via-[#ff8a00] to-[#ffe600]", shortMark: "KR", featured: true },
  { id: "release-harbour-lights", artistProfileId: "artist-marlon-tide", legacyTrackId: 2, slug: "harbour-lights", title: "Harbour Lights", genre: "Reggae", region: "Antigua & Barbuda", discoveryLane: "wadadli", creationType: "artist_made", mood: "Roots & soul", durationSeconds: 246, accentGradient: "from-[#03a678] via-[#006b5b] to-[#081c24]", shortMark: "MT", featured: false },
  { id: "release-no-apology", artistProfileId: "artist-nia-vale", legacyTrackId: 3, slug: "no-apology", title: "No Apology", genre: "R&B", region: "Antigua & Barbuda", discoveryLane: "wadadli", creationType: "artist_made", mood: "Late-night confidence", durationSeconds: 174, accentGradient: "from-[#8b3dff] via-[#5023b8] to-[#140b31]", shortMark: "NV", featured: true },
  { id: "release-bend-the-road", artistProfileId: "artist-kruz-the-bay", legacyTrackId: 4, slug: "bend-the-road", title: "Bend the Road", genre: "Dancehall", region: "Antigua & Barbuda", discoveryLane: "wadadli", creationType: "artist_made", mood: "Bass-forward energy", durationSeconds: 212, accentGradient: "from-[#ff1967] via-[#8d174c] to-[#210816]", shortMark: "KB", featured: false },
  { id: "release-sugar-mill", artistProfileId: "artist-elijah-stone", legacyTrackId: 5, slug: "sugar-mill", title: "Sugar Mill", genre: "Afrobeat", region: "Barbados", discoveryLane: "caribbean", creationType: "artist_made", mood: "Island rhythm", durationSeconds: 225, accentGradient: "from-[#00c2ff] via-[#0063cc] to-[#071d44]", shortMark: "ES", featured: false },
  { id: "release-sea-grape", artistProfileId: "artist-lani-june", legacyTrackId: 6, slug: "sea-grape", title: "Sea Grape", genre: "Alternative", region: "Dominica", discoveryLane: "caribbean", creationType: "artist_made", mood: "Soft coastal haze", durationSeconds: 189, accentGradient: "from-[#c9ff22] via-[#5e9b18] to-[#15300b]", shortMark: "LJ", featured: false },
  { id: "release-neon-mangrove", artistProfileId: "artist-mika-machine", legacyTrackId: 7, slug: "neon-mangrove", title: "Neon Mangrove", genre: "Electronic", region: "Antigua & Barbuda", discoveryLane: "ai", creationType: "ai_assisted", mood: "Future-island pulse", durationSeconds: 167, accentGradient: "from-[#dfff00] via-[#00b98f] to-[#10211c]", shortMark: "AI", featured: true },
  { id: "release-satellite-riddim", artistProfileId: "artist-nova-palm", legacyTrackId: 8, slug: "satellite-riddim", title: "Satellite Riddim", genre: "Fusion", region: "Guest Frequency", discoveryLane: "world", creationType: "ai_assisted", mood: "Global bass experiment", durationSeconds: 206, accentGradient: "from-[#7d2cff] via-[#ff2fa6] to-[#241044]", shortMark: "NP", featured: false },
] as const;
