export const contentFontFamilies = ["sans", "display", "mono"] as const;
export const contentSizes = ["small", "medium", "large", "hero"] as const;
export const contentWeights = ["normal", "semibold", "bold"] as const;
export const contentAlignments = ["left", "center"] as const;
export type SiteContentStyle = { fontFamily: typeof contentFontFamilies[number]; size: typeof contentSizes[number]; weight: typeof contentWeights[number]; align: typeof contentAlignments[number] };
export type SiteContentDefinition = { key: string; section: "home" | "discover" | "artists" | "submit_release" | "stage" | "membership" | "breaks_footer"; label: string; description: string; defaultValue: string; defaultStyle: SiteContentStyle };
const style = (fontFamily: SiteContentStyle["fontFamily"], size: SiteContentStyle["size"], weight: SiteContentStyle["weight"], align: SiteContentStyle["align"] = "left"): SiteContentStyle => ({ fontFamily, size, weight, align });
export const siteContentDefinitions: SiteContentDefinition[] = [
  { key: "home.hero.eyebrow", section: "home", label: "Hero eyebrow", description: "Short public label above the home hero.", defaultValue: "ChuneSide premiere", defaultStyle: style("sans", "small", "bold") },
  { key: "home.hero.description", section: "home", label: "Hero description", description: "Supporting sentence below the home hero headline.", defaultValue: "Wadadli leads the mix. The Caribbean joins the rhythm. Selected independent voices from around the world are welcome.", defaultStyle: style("sans", "medium", "normal") },
  { key: "discover.eyebrow", section: "discover", label: "Discover eyebrow", description: "Label above the public music discovery heading.", defaultValue: "ChuneSide radio · Discovery", defaultStyle: style("sans", "small", "bold") },
  { key: "discover.heading", section: "discover", label: "Discover heading", description: "Main heading for the public music catalogue.", defaultValue: "Find your next chune.", defaultStyle: style("display", "large", "normal") },
  { key: "artists.releases_heading", section: "artists", label: "Artist releases heading", description: "Heading used above approved music on artist profiles.", defaultValue: "Approved releases", defaultStyle: style("sans", "medium", "bold") },
  { key: "submit_release.eyebrow", section: "submit_release", label: "Submission eyebrow", description: "Short label above artist submission messaging.", defaultValue: "Artists & managers worldwide", defaultStyle: style("sans", "small", "bold") },
  { key: "submit_release.heading", section: "submit_release", label: "Submission heading", description: "Public invitation to submit music.", defaultValue: "Bring your sound to the Side.", defaultStyle: style("display", "large", "normal") },
  { key: "submit_release.description", section: "submit_release", label: "Submission description", description: "Opportunity-focused public submission copy.", defaultValue: "Send your finished track, cover artwork, short biography, social links and creation disclosure.", defaultStyle: style("sans", "medium", "normal") },
  { key: "stage.heading", section: "stage", label: "Stage heading", description: "Public Stage hero heading.", defaultValue: "Live sets. Real consent. Island-first spotlight.", defaultStyle: style("display", "hero", "normal") },
  { key: "stage.description", section: "stage", label: "Stage description", description: "Supporting copy for the public Stage hero.", defaultValue: "Short professional performance features from ChuneSide artists.", defaultStyle: style("sans", "medium", "normal") },
  { key: "membership.dialog_title", section: "membership", label: "Membership dialog title", description: "Title shown when a guest chooses a member action.", defaultValue: "Join ChuneSide to make it count", defaultStyle: style("display", "large", "normal") },
  { key: "membership.dialog_description", section: "membership", label: "Membership dialog description", description: "Safe explanation of member-only actions.", defaultValue: "Listening is open to guests. Likes and artist follows are reserved for signed-in members.", defaultStyle: style("sans", "medium", "normal") },
  { key: "breaks_footer.tagline", section: "breaks_footer", label: "Footer tagline", description: "Short public footer line. News Bar messages remain in News Bar management.", defaultValue: "From Wadadli, the Caribbean and the World.", defaultStyle: style("sans", "medium", "normal") },
];
const definitionMap = new Map(siteContentDefinitions.map((definition) => [definition.key, definition]));
export function getSiteContentDefinition(key: string) { return definitionMap.get(key); }
export function defaultSiteContent() { return Object.fromEntries(siteContentDefinitions.map((definition) => [definition.key, { value: definition.defaultValue, style: definition.defaultStyle }])); }
export function publicContentStyle(styleValue: SiteContentStyle) { return { fontFamily: styleValue.fontFamily === "display" ? "var(--font-display), Arial, sans-serif" : styleValue.fontFamily === "mono" ? "ui-monospace, SFMono-Regular, monospace" : "Arial, sans-serif", fontSize: styleValue.size === "small" ? "0.78rem" : styleValue.size === "large" ? "clamp(1.35rem, 3vw, 2.4rem)" : styleValue.size === "hero" ? "clamp(2.4rem, 7vw, 6rem)" : "1rem", fontWeight: styleValue.weight === "bold" ? 800 : styleValue.weight === "semibold" ? 600 : 400, textAlign: styleValue.align } as const; }
