import { randomUUID } from "node:crypto";
import { NextResponse } from "next/server";
import { eq } from "drizzle-orm";
import { z } from "zod";
import { requireAdminUser } from "@/app/admin-auth";
import { getDb } from "@/db";
import { adminAuditLogs, supportChunesideSettings } from "@/db/schema";
import { getSupportChuneside, supportChunesideDefaults, supportChunesideRow, type SupportChunesideDraft } from "@/lib/support-chuneside";

export const dynamic = "force-dynamic";
const schema = z.object({ action: z.enum(["save", "publish", "restore"]), enabled: z.boolean(), name: z.string().trim().min(1).max(80), message: z.string().trim().min(1).max(300), buttonText: z.string().trim().min(1).max(40), iconUrl: z.string().trim().max(500).optional().nullable(), suggestedAmounts: z.array(z.number().int().min(1).max(500)).min(1).max(6), startsAt: z.string().datetime().optional().nullable(), endsAt: z.string().datetime().optional().nullable() }).superRefine((value, ctx) => { if (value.startsAt && value.endsAt && value.endsAt <= value.startsAt) ctx.addIssue({ code: "custom", path: ["endsAt"], message: "End date must be after start date." }); });
function response(draft: SupportChunesideDraft, published: SupportChunesideDraft, status: string) { return { draft, published, status, provider: "stripe", providerConfigured: Boolean(process.env.STRIPE_SECRET_KEY), paymentSetupRequired: !process.env.STRIPE_SECRET_KEY }; }
export async function GET() { const admin = await requireAdminUser(); if (!admin) return NextResponse.json({ error: "Admin access required." }, { status: 403 }); const db = getDb(); const [row] = await db.select().from(supportChunesideSettings).where(eq(supportChunesideSettings.id, "default")).limit(1); return NextResponse.json(response(await getSupportChuneside("draft"), await getSupportChuneside("published"), row?.publishedAt ? "published" : "draft")); }
export async function POST(request: Request) { const admin = await requireAdminUser(); if (!admin) return NextResponse.json({ error: "Admin access required." }, { status: 403 }); const parsed = schema.safeParse(await request.json().catch(() => null)); if (!parsed.success) return NextResponse.json({ error: "Check the support campaign fields." }, { status: 400 }); const value = parsed.data.action === "restore" ? supportChunesideDefaults : { ...parsed.data, startsAt: parsed.data.startsAt ? new Date(parsed.data.startsAt) : null, endsAt: parsed.data.endsAt ? new Date(parsed.data.endsAt) : null }; const now = new Date(); const db = getDb(); const existing = await db.select().from(supportChunesideSettings).where(eq(supportChunesideSettings.id, "default")).limit(1); const draftFields = { draftEnabled: value.enabled, draftName: value.name, draftMessage: value.message, draftButtonText: value.buttonText, draftIconUrl: value.iconUrl, draftSuggestedAmountsJson: JSON.stringify(value.suggestedAmounts), draftStartsAt: value.startsAt, draftEndsAt: value.endsAt, updatedAt: now, updatedBy: admin.email }; try { if (!existing[0]) await db.insert(supportChunesideSettings).values({ ...supportChunesideRow(supportChunesideDefaults, now), ...draftFields }); else await db.update(supportChunesideSettings).set(draftFields).where(eq(supportChunesideSettings.id, "default")); if (parsed.data.action === "publish") await db.update(supportChunesideSettings).set({ publishedEnabled: value.enabled, publishedName: value.name, publishedMessage: value.message, publishedButtonText: value.buttonText, publishedIconUrl: value.iconUrl, publishedSuggestedAmountsJson: JSON.stringify(value.suggestedAmounts), publishedStartsAt: value.startsAt, publishedEndsAt: value.endsAt, publishedAt: now, updatedAt: now, updatedBy: admin.email }).where(eq(supportChunesideSettings.id, "default")); await db.insert(adminAuditLogs).values({ id: randomUUID(), actorId: admin.id, actorEmail: admin.email, action: `support_chuneside.${parsed.data.action}`, entityType: "support_chuneside", entityId: "default", details: JSON.stringify({ enabled: value.enabled }), createdAt: now }); return NextResponse.json(response(await getSupportChuneside("draft"), await getSupportChuneside("published"), parsed.data.action === "publish" ? "published" : "draft")); } catch { return NextResponse.json({ error: "Support settings storage is not ready. Apply migration 0022." }, { status: 503 }); } }
